# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Solace_IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


 # add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'lottie-ios'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'ReactiveKit'
pod 'Bond'
pod 'Layoutless'

  target 'Solace_IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Solace_IOSUITests' do
    # Pods for testing
  end

end
